# Generated by Django 2.2 on 2021-06-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodieMasters_app', '0002_auto_20210605_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
