# Generated by Django 2.2 on 2021-06-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodieMasters_app', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='likes', to='foodieMasters_app.User'),
        ),
    ]
