# Generated by Django 2.2 on 2021-06-10 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodieMasters_app', '0013_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('file', models.FileField(upload_to='user_images')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='upload', serialize=False, to='foodieMasters_app.User')),
            ],
        ),
    ]
