# Generated by Django 2.2 on 2021-06-11 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodieMasters_app', '0015_auto_20210611_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postimg',
            fields=[
                ('file', models.FileField(upload_to='post_images')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='food_upload', serialize=False, to='foodieMasters_app.Post')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
